### ISSUE TITLE
How to  test

### ISSUE THREAD

**Issue by O2andsAnoxia** [taeyoungson/urie#1]
Hi,thanks for your sharing.
Could you tell me what i do to test simply?such as which file i should run that i can get the enhanced picture
Thank u!

**Comment by Orangecyj** [comment]
hi, my friend, could you please tell me  where is the " srcnn_model "?

**Comment by taeyoungson** [comment]
@orange8965523 I fixed it. It won't be a problem anymore. Use the codes from the latest master branch! 
Thanks.

**Comment by taeyoungson** [comment]
@O2andsAnoxia Hi. I added render.py according to your request. It's a simple skeleton code that simply processes given image file and saves a comparison image. You can find usage of render.py in readme file. Thanks for having an interest in my work!
